"use client";

import Link from "next/link";
import { ArrowLeft, ShoppingBag } from "lucide-react";
import { CartLines, formatCartPrice, useCart } from "@/components/cart/cart-provider";

export default function CheckoutPage() {
  const { count, subtotal } = useCart();
  return <main className="min-h-screen bg-[#F7F7F8] pb-16 pt-28 text-[#1D1D1F]"><div className="nexora-container"><Link href="/shop" className="inline-flex items-center gap-2 text-sm text-[#6E6E73]"><ArrowLeft size={16} />Continue shopping</Link><h1 className="mt-6 text-3xl font-semibold">Checkout</h1>{count === 0 ? <div className="py-20 text-center"><ShoppingBag size={40} className="mx-auto text-[#86868B]" /><h2 className="mt-5 text-xl font-semibold">Your bag is empty</h2><Link href="/shop" className="mt-6 inline-flex rounded-full bg-[#1D1D1F] px-6 py-3 text-sm text-white">Select products</Link></div> : <div className="mt-10 grid items-start gap-12 lg:grid-cols-[1.2fr_1fr]">
    <section><h2 className="text-xl font-semibold">Delivery details</h2><form className="mt-6 grid gap-5 sm:grid-cols-2" onSubmit={(event) => event.preventDefault()}>{[{ name: "name", label: "Full name", autoComplete: "name", type: "text" }, { name: "email", label: "Email address", autoComplete: "email", type: "email" }, { name: "phone", label: "Phone number", autoComplete: "tel", type: "tel" }, { name: "address", label: "Street address", autoComplete: "street-address", type: "text" }, { name: "city", label: "City", autoComplete: "address-level2", type: "text" }, { name: "postal", label: "Postal code", autoComplete: "postal-code", type: "text" }].map((field) => <label key={field.name} className="text-sm font-medium">{field.label}<input name={field.name} type={field.type} autoComplete={field.autoComplete} required className="mt-2 h-12 w-full rounded-lg border border-black/10 bg-white px-4 outline-none focus:border-black/40" /></label>)}<label className="text-sm font-medium sm:col-span-2">Order notes<textarea name="notes" rows={3} className="mt-2 w-full rounded-lg border border-black/10 bg-white p-4 outline-none focus:border-black/40" /></label></form><p className="mt-6 text-sm leading-6 text-[#6E6E73]">Online ordering is not available yet. Contact NEXORA to confirm availability, delivery and payment.</p><Link href="/contact" className="mt-4 inline-flex items-center justify-center rounded-full bg-[#1D1D1F] px-6 py-3 text-sm font-medium text-white">Contact to order</Link></section>
    <section className="border-t border-black/10 pt-6 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><h2 className="text-xl font-semibold">Order summary <span className="text-sm font-normal text-[#86868B]">({count} items)</span></h2><CartLines /><div className="flex justify-between border-t border-black/10 pt-5 text-lg font-semibold"><span>Subtotal</span><span>{formatCartPrice(subtotal)}</span></div><p className="mt-3 text-xs text-[#86868B]">Delivery charges will be confirmed by our team.</p></section>
  </div>}</div></main>;
}
